config/routes.rb
Rails.application.routes.draw do
  root 'days#index'

  resources :days do
    resources :meetings
  end

  put 'meeting/:id/clear', to: 'meetings#clear', as: 'clear'

  devise_for :users

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :meetings, dependent: :destroy


  def self.from_now
    where(['date >= ?', Date.today]).order(:date)
  end
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :room
  belongs_to :day
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :meetings, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.from_now.paginate(:page => params[:page], :per_page => 7)
  end

  def new
  end

  def create
  end

  def show
    @day = Day.find(params[:id])
  end

  def edit
  end

  private

  # def day_params
  #   params.require(:day).permit(:date)
  # end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: [:clear, :show, :update, :edit]

  def index
  end

  def new
  end

  def create
  end

  def clear
    meeting_params = {title: nil, description: nil, host: nil}
    if @meeting.update(meeting_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @meeting.update(meeting_params)
      redirect_to root_path
    else
      flash[:alert] = 'Title cannot be blank'
      render :edit
    end
  end

  def show
  end

  def edit
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :description, :host, :room, :time)
  end

  def find_meeting
    @meeting = Meeting.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/days/edit.html.erb
<h1>Days#edit</h1>
<p>Find me in app/views/days/edit.html.erb</p>

app/views/days/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m12">
      <ul class="collection">
        <% @days.each do |day| %>
          <%= link_to day_path(day) do %>
           <li class="collection-item center"><%= day.date.strftime("%A - %B %u, %Y") %></li>
          <% end %>
          <% Room.all.each do |room|%>
          <% if day.meetings.where(room_id: room.id).where.not(title: nil).order('id asc').any? %>
            <li class="collection-item">
              <%= room.name %>
              <% day.meetings.where(room_id: room.id).where.not(title: nil).order('id asc').each do |meeting| %>
                <%= link_to day_meeting_path(day, meeting) do %>
                 <li class="collection-item">
                 <div class="col s4 m4 left-align"><%= meeting.display %></div>
                 <div class="col s4 m4 center"><%= meeting.title %></div>
                 <div class="col s4 m4 right-align">Hosted by: <%= meeting.host %></div></li>
                <% end %>
              <% end %>
            </li>
            <% end %>
          <% end %>  
        <% end %>
      </ul>
      <%= will_paginate @days, class: 'center' %>
    </div>
  </div>
</div>

app/views/days/new.html.erb
<h1>Days#new</h1>
<p>Find me in app/views/days/new.html.erb</p>

app/views/days/show.html.erb
<h3 class="center"> <%= @day.date.strftime("%D") %></h3>
<div class="row">
  <div class="col s12 m12">
    <% Room.all.each do |room|%>
    <div class="col s12 m4 center">
    <%= room.name %>
    <ul>
      <% @day.meetings.where(title: nil, room_id: room.id).order('id asc').each do |meeting| %>
         <li><%= link_to meeting.display, edit_day_meeting_path(@day, meeting), class: 'btn' %></li>
         <% end %>
    </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo center"><%= image_tag('black.png', class: 'logo', :alt => "Church&State") %></a>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Church and State Room Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body class="teal lighten-5">
<span class="notice"><%= notice %></span>
<span class="alert"><%= alert %></span>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Church and State</h5>
         <a class="right cs"><%= image_tag("bundle.png", :alt => "Church&State") %></a>
          <p class="grey-text text-lighten-4">
          We are a 501 (c) (3) non-profit organization - a community managed entrepreneur center that offers free space and resources to entrepreneurs with nothing expected in return.
          </p>
      </div>
    </div>
  </div>
    <div class="footer-copyright">
      <div class="container">
        © 2015 Church and State All Rights Reserved
      </div>
    </div>
  </div>
</footer>
</html>

app/views/meetings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m10 offset-m1 center">
      <h3><%= @meeting.display %></h3>
      <h4><%= @meeting.room.name %></h4>
      <% if user_signed_in? %>
        <%= form_for [@meeting.day, @meeting] do |f|%>
          <br />
      ​
          <div class="field">
              <%= f.label :title %><br />
              <%= f.text_field :title, required: true %>
          </div>
      ​
          <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description %>
          </div>
      ​
          <div class="field">
              <%= f.label :host %>
              <%= f.text_field :host %>
          </div>
      ​
          <br />
          <%= f.submit 'Submit', class: 'btn', onclick: "Materialize.showStaggeredList('#staggered-test')" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<h1>Meetings#index</h1>
<p>Find me in app/views/meetings/index.html.erb</p>

app/views/meetings/new.html.erb
<h1>Meetings#new</h1>
<p>Find me in app/views/meetings/new.html.erb</p>

app/views/meetings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m12 center">
      <h3><%= @meeting.title %></h3>
      <h4><%= @meeting.display %></h4>
      <p>Hosted by: <%= @meeting.host %></p>
      <p><%= @meeting.description %></p>
      <p><%= @meeting.room.name %></p>

      <%= link_to 'Edit Meeting', edit_day_meeting_path(@meeting.day, @meeting), class: 'btn', onclick: "Materialize.showStaggeredList('#staggered-test')" %>

      <%= link_to 'Cancel Meeting', clear_path(@meeting), class: 'btn', onclick: "Materialize.showStaggeredList('#staggered-test')", method: :put %>
    </div>
  </div>
</div>